mustang-im/mustang

app/logic/Mail/EWS/EWSAccount.ts, backend/backend.ts
- Only handles changes for email, not calendar or contacts
- Doesn't handle folder removal
=> EWS: Push mail (#73)

app/frontend/Calendar/EventLine.svelte, app/frontend/Mail/Composer/Attachments/AttachmentEntry.svelte, app/frontend/Mail/Message/MessageToolbar.svelte, app/frontend/Mail/Search/SearchPane.svelte, app/frontend/Settings/Mail/Account/IdentityBlock.svelte, app/logic/Contacts/AccountsList/SQL.ts, app/logic/Mail/Virtual/AllAccounts.ts
**Changes**
- Add missing translations
- Fix review comments in #111
=> Translation: Add and fix UI translation

.github/workflows/crowdin-download.yml, .github/workflows/crowdin-upload.yml, app/l10n/README.md, app/l10n/crowdin.yml
**Changes**
- Added `Crowdin Upload` which only uploads the source
- Added `Crowdin Download` which only downloads the translations
=> Crowdin AI translation CI

app/logic/Mail/AutoConfig/saveConfig.ts
Fixes https://github.com/mustang-im/mustang/issues/117#issuecomment-2221615335
=> Fill OAuth username before login with OAuthUI

app/logic/Mail/AutoConfig/saveConfig.ts
Fixes https://github.com/mustang-im/mustang/issues/117#issuecomment-2224114810
=> Check if OAuth2 instance exist before assigning username

.github/workflows/release-linux-parula.yml, e2/electron-builder.yml
**Changes**
- Add write permission for repo content to the job
- Set releaseType to release
**TODO**
- Release workflow for other OSes
- Should we auto generate the release description/CHANGELOG?
=> Release workflow

app/logic/Abstract/Account.ts, app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/Contacts/OWA/OWAPerson.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/OWAEMail.ts, app/logic/Mail/OWA/OWAFolder.ts, backend/owa.ts
Plus I noticed that multiple calendars caused the data to get mixed; this was because the code was trying to reuse the same account id for each calendar.
=> Persist OWA data to database, support push mail

app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/OWA/OWAFolder.ts
Contains the fix from e36e1d2 but applied to the other two problem places.
=> List all new messages, not just the last iteration

app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
As per comments on 4477457.
(Seriously, is there no way to map over a Map?)
=> Send all extra MIME headers

app/logic/Mail/EWS/EWSEMail.ts, app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/OWA/OWAEMail.ts, app/logic/Mail/OWA/OWAFolder.ts, app/logic/Mail/Tag.ts
Also fix a JSON parse error I hit trying to start the app up.
=> Save tags as categories #177

app/frontend/Settings/Setup/Mail/manual/ProtocolSelector.svelte, app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/ActiveSync/ActiveSyncEMail.ts, app/logic/Mail/ActiveSync/ActiveSyncFolder.ts, app/logic/Mail/ActiveSync/WBXML.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/OWA/OWAFolder.ts, app/logic/Mail/SQL/SQLEMail.ts, app/logic/util/util.ts, app/package.json, backend/backend.ts, lib/jpc/obj.js
Supported features:
- Provision ActiveSync device
- Send mail using MIME source
- Push notifications
- List folders
- Create, rename, move, delete folders
- List messages
- Read some basic message properties
- Read message source
- Mark message read or starred
- Tag message
- Move or delete message
Not supported:
- Copy message
- Create draft
- Mark all messages read
=> ActiveSync: EMail

app/logic/Mail/ActiveSync/ActiveSyncFolder.ts, app/logic/Mail/Folder.ts, app/logic/Mail/SQL/EMailCollection.ts
The base type had been changed by commit 8e4cbc78191101a29bfd284ecfe55bf1d0ed99b8.
=> Fix type of messages property of ActiveSyncFolder

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
- EWS, OWA, ActiveSync: Compare username with username
=>  EWS, OWA, ActiveSync: Don't compare username with emailAddress #226 

app/logic/Calendar/Calendar.ts, app/logic/Calendar/SQL/SQLCalendar.ts, app/logic/Calendar/SQL/SQLStorage.ts, app/logic/Calendar/Store/setStorage.ts, app/logic/Contacts/Addressbook.ts, app/logic/Contacts/SQL/SQLAddressbook.ts, app/logic/Contacts/SQL/SQLStorage.ts, app/logic/Contacts/Store/setStorage.ts, app/logic/Mail/MailAccount.ts
This is a fix for https://github.com/mustang-im/mustang/commit/32c2687493dad9870a00dc7451b734e157bcb511#r147825086
=> Calendar and AB: setStorage()

app/logic/Abstract/Group.ts, app/logic/Abstract/Person.ts, app/logic/Calendar/EWS/EWSCalendar.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Contacts/ActiveSync/ActiveSyncAddressbook.ts, app/logic/Contacts/ActiveSync/ActiveSyncPerson.ts, app/logic/Contacts/EWS/EWSAddressbook.ts, app/logic/Contacts/EWS/EWSGroup.ts, app/logic/Contacts/EWS/EWSPerson.ts, app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/Contacts/OWA/OWAGroup.ts, app/logic/Contacts/OWA/OWAPerson.ts
- Separate save() to DB and saveToServer() for OWA, EWS and ActS calendar and addressbook
- Separate delete() to DB and deleteFromServer() for OWA, EWS and ActS calendar and addressbook
=>  OWA, EWS, ActS: separate save() to DB and saveToServer() #234 

app/frontend/Calendar/EditEvent/EditEvent.svelte, app/frontend/Contacts/PersonMenu.svelte, app/logic/Abstract/Group.ts, app/logic/Abstract/Person.ts, app/logic/Calendar/Event.ts
I don't really know how you want this to work, but it's a start.
=> Actually save events and contacts to the server

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
Just creating the object isn't enough any more, so I'm using `newXForProtocol` which will set up the storage as well.
=> Ensure newly discovered addressbooks and calendars have storage

app/logic/Calendar/EWS/EWSCalendar.ts, app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Contacts/ActiveSync/ActiveSyncAddressbook.ts, app/logic/Contacts/EWS/EWSAddressbook.ts, app/logic/Contacts/OWA/OWAAddressbook.ts
As mentioned in the aforementioned commit these calls are just to update our local copy of the object from the server.
=> EWS, OWA, ActS: When changes are coming from server, don't push them back to the server

app/logic/Contacts/JSON/JSONAddressbook.ts, app/logic/Contacts/JSON/JSONGroup.ts, app/logic/Contacts/JSON/JSONPerson.ts
Implemented the `JSON*` classes that'll be used for AceBase
=> Addressbook: JSON* classes

app/logic/Calendar/Event.ts, app/logic/Calendar/JSON/JSONCalendar.ts, app/logic/Calendar/JSON/JSONEvent.ts
JSON: Calendar: Add implementations
- JSONCalendar
- JSONEvent
=> JSON: Calendar: Add implementations

backend/acebase.ts
- The functions are missing awaits.
- We also need to add await to the `forEachFiltered()` function in #252
=> Acebase: Missing awaits

app/logic/Mail/JSON/JSONMailAccount.ts
- add outgoingAccountID because that's the name used in Acebase
- add workspaceID
=> JSONMailAccount: Add outgoingAccountID & workspaceID

app/logic/Mail/AceBase/AceEMail.ts, backend/acebase.ts
- from PR #252
- added missing await to `forEachFiltered()` in acebase.ts
=> AceBase: Emails filtered

app/logic/Mail/IMAP/IMAPAccount.ts
Alternative to #298 
This is completely untested. I don't have a Gmail account to test with. @jermy-c could you please test this? And if it doesn't work, fix the code?
=> IMAP: Don't show [Gmail] folder - fixes #285

app/logic/Contacts/EWS/EWSGroup.ts, app/logic/Contacts/OWA/OWAGroup.ts, app/logic/Mail/EWS/EWSEMail.ts, app/logic/Mail/OWA/OWAEMail.ts
So my previous workarounds are no longer necessary.
=> replaceAll is now available on SetColl

app/frontend/Shared/WebView.svelte, backend/backend.ts
- Listens to click events in the webview and invokes a click event on the webview element this closes all context menus
**Bugs**
- Occasionally you'll see a hover effect over an email on the email list if you're in the three column view
=> Webview: Bubble click event to the main window

app/frontend/Shared/WebView.svelte
- Opens links in system browser
- Why did I do it this way? `did-start-navigation`,  `will-frame-navigate`, `will-navigate`, `did-frame-navigate`, `did-navigate` events don't trigger nor does `did-create-window`
- The other way might be to use `<webview>.executeJavaScript(code[, userGesture])` and have it send the URL to the main window.
=> Open links in system browser (#191)

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
This might be the cause of #282.
=> ActiveSync: Stop creating duplicate calendars

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts
I accidentally overlooked this file when I created PR #354.
=> Disassociate more Scheduling values from ActiveSync protocol values

app/frontend/Mail/Message/MessageMovePopup.svelte, app/logic/Mail/EWS/EWSCreateItemRequest.ts, app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/OWA/OWAFolder.ts
Also some minimal (! - I couldn't work out how to show more than one account at once) UI for actually copying messages between accounts...
OWA's `moveOrCopyMessagesOnServer` was actually broken, which is a shame, as i needed a copy of the code for uploading (OWA can only upload messages to the Drafts folder), so I had to fix that first.
I also improved some of the parameter type definitions.
=> EWS/OWA: Upload MIME message #375 #376

app/logic/Mail/OWA/OWAFolder.ts
It dawned on me that the reason I'd previously been unable to add messages directly to target folders is that I hadn't figured out the relation between EWS and OWA naming.
In EWS, the destination folder is introduced using the `SavedItemFolderId` element. This element accepts one of two child elements, `FolderId` (whose `Id` attribute is a full EWS folder ID) or `DistinguishedFolderId` (whose `Id` attribute is a shorthand name for one of the predefined EWS folders).
In OWA, the destination folder is introduced using the `SavedItemFolderId` property whose value should be an OWA object whose `__type` is `TargetFolderId:#Exchange`. This object has one property which is always called `BaseFolderId`, however its value is then an OWA object whose `__type` can be either `FolderId:#Exchange` or …
=> Properly add messages #376

app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
ActiveSync is trickier; it normally doesn't have this problem, but it would do if we ever get a status 9.
=> EWS, OWA: Synchronise folder deletions from the server during login #420

app/frontend/Mail/Composer/IdentitySelector.svelte, app/frontend/Mail/Composer/MailComposer.svelte
Particularly relevant for Exchange accounts which typically don't let you fake the from address.
I'm also updating the name as well.
=> Always set the from address when changing identity

app/build/parula-brand.sh, e2/electron-builder.yml
- Rename package name for Mustang
=> Build: Linux: Rename package name for Mustang (#473)

app/logic/Calendar/OWA/Request/OWACreateOffice365EventRequest.ts, app/logic/Calendar/OWA/Request/OWAEventRequests.ts, app/logic/Calendar/OWA/Request/OWAUpdateOccurrenceRequest.ts, app/logic/Calendar/OWA/Request/OWAUpdateOffice365EventRequest.ts, app/logic/Calendar/OWA/Request/OWAUpdateOffice365OccurrenceRequest.ts, app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/Contacts/OWA/Request/OWACreatePersonaRequest.ts, app/logic/Contacts/OWA/Request/OWADeletePersonaRequest.ts, app/logic/Contacts/OWA/Request/OWAPersonRequests.ts, app/logic/Contacts/OWA/Request/OWAUpdatePersonaRequest.ts, app/logic/Mail/OWA/Notification/OWAOffice365Notifications.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/OWAFolder.ts, app/logic/Mail/OWA/Request/OWACreateItemRequest.ts, app/logic/Mail/OWA/Request/OWADeleteItemRequest.ts, app/logic/Mail/OWA/Request/OWAFolderRequests.ts, app/logic/Mail/OWA/Request/OWARequest.ts, app/logic/Mail/OWA/Request/OWASubscribeToNotificationRequest.ts, app/logic/Mail/OWA/Request/OWAUpdateItemRequest.ts
Fixes #485 and also fixes #488.
=> Commits lost when Ben merged #458 to master

app/logic/Calendar/ICal/ICalEMailProcessor.ts, app/logic/Calendar/ICal/ICalGenerator.ts, app/logic/Calendar/RecurrenceRule.ts, app/logic/Calendar/SQL/SQLEvent.ts
These were found while writing tests based on libical's test data.
- 0fa5ef0 Detect the organiser case-insensitively
- 76625b5 Don't try to detect the organiser twice
- 6ae3265 Recurrence rule should be parsed case-insensitively
- 92b32cf Recurrence rule needs to output recurrence end in allDay format
- c68d52f Correctly handle all-day events
=> Fix some bugs converting from parsed iCal to mustang Event object

app/logic/Contacts/ActiveSync/ActiveSyncAddressbook.ts, app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/ActiveSync/ActiveSyncFolder.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/OWAFolder.ts
Is this the sort of thing you were looking for in your comment on a48b133?
=> Comment on some differences between Exchange protocols

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSCalendar.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/ICal/ICalEMailProcessor.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/OWA/Request/OWAEventRequests.ts
ActiveSync, EWS, OWA: Read timezone from server events
Invitations: Read timezone from .ics attachment and handle invitations given in local time
=> Add some more timezone support

app/.gitignore, app/package.json
- Npm script to use https://github.com/mustang-im/json-autotranslate/pull/2
- Fix Git Ignores for L10n files
=> L10n: Auto-Translate: Include context for messages: Adapt Build script

app/logic/Calendar/JSON/JSONEvent.ts, app/logic/Calendar/SQL/SQLEvent.ts
=> Save timezone to database

app/frontend/Calendar/DisplayEvent/Invitation.svelte, app/frontend/Calendar/EditEvent/DialogHeader.svelte, app/frontend/Calendar/EditEvent/EditEvent.svelte, app/frontend/Calendar/EditEvent/InvitationResponseButtons.svelte, app/frontend/Calendar/EditEvent/PersonResponse.svelte, app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/ICal/ICalEMailProcessor.ts, app/logic/Calendar/ICal/ICalGenerator.ts, app/logic/Calendar/Invitation.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/Participant.ts, app/logic/Mail/ActiveSync/ActiveSyncEMail.ts, app/logic/Mail/EMail.ts, app/logic/Mail/EWS/EWSEMail.ts, app/logic/Mail/MailAccount.ts, app/logic/Mail/OWA/OWAEMail.ts, app/logic/Mail/SQL/createDatabase.ts
Don't ask me where those values in the comment in `Mail/SQL/createDatabase` came from...
=> Clarify invitation types

app/TODO.md, app/logic/Abstract/Account.ts, app/logic/Calendar/Calendar.ts, app/logic/Chat/ChatAccount.ts, app/logic/Contacts/Addressbook.ts, app/logic/Mail/AccountsList/MailAccounts.ts, app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/AutoConfig/guessConfig.ts, app/logic/Mail/AutoConfig/manualConfig.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/IMAP/IMAPAccount.ts, app/logic/Mail/Import/Thunderbird/TBProfile.ts, app/logic/Mail/MailAccount.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/POP3/POP3Account.ts, app/logic/Mail/SMTP/SMTPAccount.ts, app/logic/Mail/SQL/Account/SQLAccount.ts, app/logic/Mail/SQL/SQLMailAccount.ts, app/logic/Meet/MeetAccount.ts
Part of #155. Followup to #573.
=> SMTP: Use mailAccount to link to IMAP/POP3 account - fixes #155

app/test/logic/Contacts/VCard/TestData/rfc6350.json, app/test/logic/Contacts/VCard/TestData/rfc6350.vcf, app/test/logic/Contacts/VCard/VCard.ts
=> Strip leading tel: when parsing vCards

backend/backend.ts
- Access the app directory only, app data should be saved within the app directory only
=> Mobile backend: Point to app dir

app/test/logic/Contacts/VCard/TestData/Apple.json, app/test/logic/Contacts/VCard/TestData/Proton.json, app/test/logic/Contacts/VCard/TestData/Thunderbird.json, app/test/logic/Contacts/VCard/TestData/rfc6350.json, app/test/logic/Contacts/VCard/VCard.ts, app/test/logic/Contacts/VCard/VCardParser.test.ts
- Updates parsed Person with test data
- Serialises result to string
- Checks that serialisation includes test data
- Checks that serialisation includes data we don't parse from original test file
- Check that serialisation parses
=> VCard parser tests, part 3

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts
The call to `listEvents` turned out to be unreliable. I looked into trying to fix it, but I was unsuccessful, so I resorted to performing a round-trip to get the UID.
The `queryServer` function will also allow a round-trip check to be made, but that's a separate PR.
=> ActiveSync: Really find calUID

app/logic/Calendar/ActiveSync/ActiveSyncOutgoingInvitation.ts
You did say you wanted PRs to be as small as possible...
=> ActiveSync: Calendar: Outgoing Invitation: Fix typo

app/package.json
- Use dynamic option for decoding escapes
=> Auto translate: Use dynamic option for decoding escapes (#614)

app/logic/Contacts/VCard/NOTES.md, app/test/logic/Contacts/VCard/NOTES.md, app/test/logic/Contacts/VCard/TestData/Google.json, app/test/logic/Contacts/VCard/TestData/Google.vcf
- Add Google contacts test sample and expected result
- Add Notes for vCard
=> vCard: Google test sample (#563)

app/test/logic/Calendar/ICal/ICalEMailProcessor.test.ts, app/test/logic/Calendar/ICal/TestData/icaljs-test5-2.json, app/test/logic/Calendar/ICal/TestData/rfc6047-3.json, app/test/logic/Calendar/ICal/TestData/rfc6047-5.json
- Add missing empty string descriptionText property
- Fix TS errors in the code
- Fix params in the wrong place for `readFile()`
=> Test: ICalEMailProcessor: Fix test errors and TS errors

app/logic/testData.ts
- FakeData for Email works, moving, saving, editing emails work
- FakeData for Files work
- FakeData for Event not working yet, missing organizer error
=> Test: FakeData

app/frontend/Calendar/DayView/EventsBlockCell.svelte, app/frontend/Calendar/DayView/WeekView.svelte, app/frontend/Calendar/MonthView/EventsLineCell.svelte
> FYI, the change in git commit f71507f was necessary, because the calendar.events were not observed anymore and therefore events added/remove were not showing up. This change fixed a good number of bugs, and should stay. Please fix the current code based on that.
Sorry, but this was never true; the events collection had never been observed which is why nothing happened when events were asynchronously added or deleted.
With these changes, when I click the Sync button all of the additions and deletions show up as expected. (Other changes sometimes show up and sometimes don't, so I suspect there are more places where events aren't being properly observed.)
=> Observe when events are added or removed

app/logic/Calendar/OWA/OWAEvent.ts
OWA doesn't seem to like it any more either.
Compare #536.
=> Don't try to unset the recurrence of an instance

app/logic/Contacts/EWS/EWSPerson.ts, app/logic/Contacts/OWA/OWAPerson.ts
- Fix reading and saving the post code in EWS
- Fix deleting address in OWA
- Fix field order when saving the post code in OWA
- No issues found with ActiveSync
=> Exchange: Contacts: Fix street addresses

app/frontend/Calendar/EditEvent/DialogHeader.svelte
1. Click create an event
2. Select a different calendar than the initially selected
3. Click to add any of the following: Repeat, Reminder, Invite, Location, Online meeting, Description
- Selected calendar reverts back to initially selected calendar
- Selected calendar stays the same
=> Calendar: Edit: Move calendar - after introducing unedited

app/logic/Calendar/Invitation/IncomingInvitation.ts, app/logic/Mail/MailAccount.ts
if the event isn't in your calendar, look at the participants to see whether you are the organiser.
Or should I look at the organiser to see whether that's you? Well, we already have code that does the first approach; I just had to move it somewhere where I could call it.
=> Try harder to detect outgoing invitations

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
=> ActiveSync: Wait for sync before restarting Ping #769

app/frontend/Setup/Shared/OAuth2Login.svelte, app/frontend/Shared/Auth/OAuth2EmbeddedBrowser.svelte, app/logic/Auth/LoginAutoFill.ts
In PR #815 I accessed the web based auth auto fill script from its location in OWA; this PR moves it into a more suitable location and tweaks the parameters.
Also sorry for the invalid comment in the CSS.
=> Login auto fill tweaks #814

app/logic/Auth/LoginAutoFill.ts
As mentioned in PR #824, this makes auto fill work for the on premise Exchange server UI.
=> OWA: Auto Fill for on premise Exchange servers

mobile/docs/build.md
- Document steps to build for android
=> Android docs

app/frontend/Util/route.ts, app/l10n/l10n.ts, app/logic/Abstract/Group.ts, app/logic/Abstract/Person.ts, app/logic/Auth/OWAAuth.ts, app/logic/Chat/XMPP/XMPPAccount.ts, app/logic/Chat/XMPP/XMPPChat.ts, app/logic/Files/File.ts, app/logic/Mail/EMail.ts, app/logic/Mail/Graph/GraphAccount.ts, app/logic/Mail/JMAP/JMAPFolder.ts, app/logic/Meet/LocalMediaDeviceStreams.ts, app/logic/Meet/StartCall.ts, app/tsconfig.json
Note: `l10n.ts` code was actually incorrect, and never tried the default message. As for the other cases, I did have to guess the intent for most of them, except for `OWAAuth.ts`, which was definitely an error on my part.
=> Turn on noImplicitReturns TypeScript type checking #841

app/frontend/Shared/ContextMenu.ts, app/l10n/generateMessageID.ts, app/l10n/l10n.ts, app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSCalendar.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/ActiveSync/WBXML.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/EWS/EWSEMail.ts, app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/OWA/OWAEMail.ts, app/logic/startup.ts, app/logic/util/RunOnce.ts, app/logic/util/netUtil.ts, app/logic/util/util.ts, lib/util/sanitizeDatatypes.ts
Found by `tsc --noImplicitAny`.
=> Add missing parameter type declarations #841

app/logic/Mail/EMail.ts, app/logic/Mail/Folder.ts, app/logic/Mail/Graph/GraphFolder.ts, app/logic/Mail/JMAP/JMAPFolder.ts
=> Fix incorrect template strings #841

app/logic/Mail/EMail.ts
=> Mail: Lock loadBody()

app/frontend/Contacts/PersonAutocomplete/PersonPopup.svelte, app/frontend/Mail/Message/Recipient.svelte, app/logic/Abstract/PersonUID.ts
- We were only adding the person to the collection and not saving to disk or remotely
- This fixes **Reproduction 1** of #874
=> Mail: Save recipient to disk and remotely

app/logic/build.ts
I wish there was a way to tell `git` not to accidentally commit changes to the file but apparently there isn't.
=> App should not be mobile by default
