app/logic/Mail/IMAP/IMAPEMail.ts, lib/jpc/message.js
Steps to reproduce problem:
- Don't download all messages in a folder in advance
- Delete a message in a folder
- Read a message with a higher sequence number
Expected results: Message you selected is downloaded
Actual results: Message you selected is overwritten by an unrelated message that now has that sequence number, causing it to become cloned
This is why UIDs were invented, after all...
Well, except when expunging messages; sadly the response only mentions the sequence number of the message, as using or including the UID wouldn't be backwards compatible.
Thunderbird's JavaScript IMAP client works around this by simply refreshing the entire folder if it gets an expunge notification from the server.
Thunderbird's C++ IMAP client keeps an array of the UIDs so that it can always …
=> IMAP sequence numbers are unstable #120

app/logic/Auth/OAuth2.ts, app/logic/Mail/AutoConfig/readConfig.ts, app/logic/Mail/AutoConfig/saveConfig.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/IMAP/IMAPAccount.ts, app/logic/Mail/Import/Thunderbird/TBProfile.ts, app/logic/Mail/MailAccount.ts
Alternative fix for issue #117, instead of PRs #130 and #131
=> OAuth2: Use the username and password from the account. Don't duplicate it.

e2/electron-builder.yml, e2/package.json
**Changes**
- Remove AppImage param from `build:release:linux` script so it uses the targets in `e2/electron-builder.yml`
- Comment out `snap` target in `e2/electron-builder.yml` because it tries to publish to Snap instead of GitHub and also it needs `snapcraft` to be installed. It causes errors also.
Draft release generated by the action: https://github.com/mustang-im/mustang/releases/tag/untagged-beaee3af94b3a3e82b90
=> Include .deb and .rpm artifacts in release

e2/package.json, e2/src/main/index.ts
- Call `autoUpdater.checkForUpdatesAndNotify();` when app is ready. Check for updates, notify and install on exit.
Note: Doesn't work on Mac OS X, yet.
=> Check for updates, notify and install on exit

e2/electron-builder.yml
- Set channel name to `mustang`, it changes the `latest.yml` to `mustang.yml`
- The script in `app/build/parula-brand.sh` changes the channel to `parula`
=> Set channel name to mustang

app/logic/Mail/OWA/OWAAccount.ts
We default to clearing server cookies if there is an authentication failure response from an OWA call. This does have the unfortunate side-effect that the login window also forgets who you are, but I don't know a better way to reset the cookies to a known state.
However in the case that we know we have failed automatic login (non-Office 365 account, or didn't select "Stay Logged In"), but the user attempted to access OWA anyway, then we can fast fail the OWA call and avoid clearing cookies. This allows the username to be remembered for when the user clicks Get Mail to open the OWA login window.
=> OWA: Fast fail until account has logged in #157

app/logic/Mail/EWS/EWSAccount.ts, app/logic/util/util.ts
I couldn't get this to trigger using the STR in #121 but what I was able to do was as follows:
- Delete `~/.mustang/mail.db`
- Set up the account when prompted
- Click on a miscellaneous folder in the account itself
- Click on All Accounts
This seems to trigger a list of every single folder in the account in parallel, thus triggering the server busy error. (This doesn't happen after a restart; you have to do it in the same session.)
=> Honour suggested backoff time #95 #121

.github/workflows/installer-mac-parula.yml, .github/workflows/installer-mac.yml, e2/build/entitlements.mac.plist, e2/electron-builder.yml
- Set notarize to true in electron-builder.yml
- `<key>com.apple.security.cs.disable-library-validation</key> <true/>` to fix "Team ID doesn't match" error after app is signed
- Add code-signing and notarization steps to workflow
Note: Notarization step not tested on CI yet
=> Mac: Code Signing

app/logic/Auth/OAuth2.ts
Fix:
-  Yahoo account not re-logging in after restart.
- `Error: Missing code verifier`
=> OAuth2: dont' send code_verifier when getting a refresh token

e2/electron.vite.config.ts, e2/package.json, e2/src/main/index.ts, lib/jpc-ws/protocol.js
- update better-sqlite3 to 11.2.1 since older versions don't work with electron@32
- update electron-vite to 2.3.0 to support ESM
- update electron to 32.0.1 to support ESM
- use custom ESM shim plugin since the one in `electron-vite` doesn't seem to work nor the `@rollup/esm-shim` plugin, therefore causing the `__dirname` syntax error
- fix syntax errors to be compatible with ESM
- set the config to output ESM for `main` and `preload` scripts
- in the main script set the `preload` to mjs because it outputs it with the`mjs` file extension for some reason
Where should we point the `esm-shim-plugin` package? It is a package based on https://github.com/rollup/plugins/issues/1709#issuecomment-2112362911. Will it be moved to Mustang?
=> e2: Output ESM instead of CJS for main and preload scripts

app/frontend/Mail/LeftPane/LeftPane.svelte
- Do nothing on TagList clear event
=> Fix: Search: UI freezes after loading an email folder then clicking search

app/TODO.md, app/frontend/Mail/3pane/TableMessageListItem.svelte, app/frontend/Mail/Vertical/VerticalMessageListItem.svelte, app/logic/Mail/EMail.ts, app/logic/Mail/EWS/EWSEMail.ts, app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/IMAP/IMAPEMail.ts, app/logic/Mail/IMAP/IMAPFolder.ts, app/logic/Mail/OWA/OWAEMail.ts, app/logic/Mail/OWA/OWAFolder.ts, app/logic/Mail/SQL/SQLEMail.ts, app/logic/Mail/Store/MailZIP.ts
Fixes MIME source not yet downloaded #188
`downloadCompleted` is true, but the body fields are empty in the DB.
We do a `save()` of that half-loaded message. And that save is overwriting the complete msg in the DB with the half-loaded one.
It appears there are at least 2 code paths that do that: `IMAPFolder.updateNewFlags()` and `IMAPFolder.messageFlagsChanged()`. They are called e.g. when the read status changes, or flags are added. Both call `await this.saveMsgs(updatedMessages)` (not new msgs). `SQLEMail.save()` then overwrites the existing message. That's the bug.
That's because `SQLEMail.readAll()` reads the headers, but not the body. So, `downloadComplete` will be read as `true`, but the body will still be empty - in memory. Doing `SQLEMail.save()` will the save a broken and …
=> IMAP: Don't overwrite full msg in DB with half-loaded msg in memory

app/frontend/app.css
It seems like Chrome ignores all ::webkit-scrollbar if there's a single `scrollbar-*` css rule. So I just removed a single style in the body selector.
https://syntackle.com/blog/changes-to-scrollbar-styling-in-chrome-121/
=> Fix scrollbar styles overridden by scrollbar-color

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/IMAP/IMAPFolder.ts, app/logic/Mail/SQL/SQLEMail.ts
This is a race condition. `listFolders` only saved the folders asynchronously, so they were still in the process of being saved when `listMessages` was called on the "Sent Items" folder. Since the folder hadn't been saved yet, `readFolder` tried to save it again, with hilarious consequences.
(See comments in #203 regarding the other two changes.)
=> Fix SQL error during ActiveSync account creation - fixes #204

app/frontend/Chat/MessageView/Message.svelte, app/frontend/Shared/WebView.svelte
- `<webview>` is now resizable but by passing in a maxWidth from the parent
- `<webview>` doesn't respect max-width like an iframe so we need to get it from the parent element
- It gets the size only at the first load of the content. After that, it adjusts the width based on the max-width, this should make it much lighter.
- Inject CSS when generating the data:URI so it doesn't reflow
Known Issues:
- The height is still not accurate, and some times the width.
- The height grows every time you switch a chat/person because reuses the same webview and 'fit-content' property fills space available and when we add the buffer it'll become larger. After that, webview is bigger and adds the buffer again.
- The resizing lags sometimes
=> Chat viewer: webview resizable

app/logic/Mail/OWA/OWAAccount.ts, backend/owa.ts
- `JSON.parse()` normally throws an error when parsing an empty string or null
- `response.json()` under the hood uses `JSON.parse()` so it'll throw an error when it's empty
- `json.cid` would throw an error if json is null so we just use `json ? json.cid : null` to prevent that
=> OWA: Don't throw "end of json" error for response.json() - fixes #215

app/logic/Mail/OWA/OWALoginAutoFill.ts
The preferred way to "uneval" a value to be evaluated through `executeJavaScript` appears to be `JSON.stringify` (obviously assuming that the value has a JSON-safe type in the first place). Note that this includes any quotes (or other necessary metacharacters where relevant) so those aren't needed in the template string.
As for the function, it's clearer simply to wrap the function declaration in parentheses, as this turns it into an expression instead. And as a function expression, we can then pass arguments to it, which makes the value injection even clearer still.
=> Properly escape variables injected into auto fill script #157

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/OWALoginBackground.ts
- For EWS and ActiveSync, assume that `username` is set, without trying to fall back to `emailAddress`
- For OWA, always use `username` for logging in, not `emailAddress`
=> EWS, OWA, ActS: Use account username consistently

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
After logging into an ActiveSync account no folders are displayed.
- `listFolders()` was removed in `login()`
=> ActiveSync: No folders fix

app/logic/Contacts/ActiveSync/ActiveSyncAddressbook.ts, app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/ActiveSync/ActiveSyncFolder.ts, app/logic/Mail/ActiveSync/WBXML.ts
Commit 893ad47 is the main part of the PR, it moves processing of received data to a callback which is called before the sync key is saved, so if there is an error processing we can retry.
Commit 520f29b is because I decided that the looping to obtain additional results was awkward. Instead of having a clunky while loop which checks for `MoreAvailable`, I moved the loop into the `makeSyncRequest` functions.
Commit 5a595d3 just fixes a console warning I happened to notice at the time.
Note that you may find it easier to view the commits with whitespace hidden.
=> Activesync: Save sync key later

app/tsconfig.json
For some curious reason, after the removal of the line `import { SQLMailAccount } from "../SQL/SQLMailAccount";` by commit 0056359113c4a0701d4e1c2289cb0f52e7b40008, typescript no longer bothers to check my code, which is unfortunate. I found this addition to be the simplest solution for me.
=> Make my tsc find all the logic files again

app/logic/Calendar/Event.ts
#172 changed `instances` from an array to a `Collection` but I spotted a use that was missed. (And my TypeScript did't complain either...)
=> Fix missed instance of change to collection from #172

app/logic/Calendar/RecurrenceRule.test.ts, app/logic/Calendar/RecurrenceRule.ts
The bug occurs when we fill more occurrences (so they have to be filled twice). This doesn't normally happen because both the front and back end code try to fill a couple of years at once to avoid having to fill more occurrences. However if the last filled occurrence was moved to the last day of a short month then the fill code would erroneously continue from that day
=> Fix recurrence rule short month bug

app/logic/Mail/JSON/JSONEMail.ts, app/logic/Mail/JSON/JSONFolder.ts
I changed property names in the `read()` methods for the `JSON*` classes because they are different than the ones in the `save()` methods making them read properties that contain `null` values.
This fixes a bug where all the emails have the date and time of the current time when viewing the emails.
=> JSONEmail & JSONFolder: Read & write property names don't match

app/logic/Mail/AceBase/AceEMail.ts, backend/acebase.ts
All emails are iterated regardless if they belong in the folder. I add a `forEachFiltered()` method to the AceBaseHandle and used that to only iterate through emails that belong in the Folder.
=> AceBase: Emails filtered

app/logic/Mail/JSON/JSONFolder.ts
This should fix this error:
```
MalformedException: Value error: Not alpha-num-dash (Bad value: AAMkAGY0MGQ5Mzg4LWExYTctNGMzNi1iOTYyLTJiNTgzZTIxM2M1MwAuAAAAAAAYEBsALqIRR4Wuv0+L/Y7AAQA4Jj9yBgAgRLf4U7C0SL8uAAGZjbZ+AAA=) ⁠
```
and also the property name for the parent folder is `parentID` not `parent`
=> JSONFolder: Use id instead of dbID

app/logic/Mail/AceBase/AceFolder.ts
- Use folder id instead of dbID
- The property name for the parent folder is incorrect, it should be `parentID`
- JSONFolder is not an async function
=> ACEFolder: Fix id property names

app/logic/Mail/AceBase/AceEMail.ts, backend/acebase.ts
- emails were not ordered correctly by date in descending order
- this adds the option to do that
- it creates an index before doing the query otherwise it would be very slow, because sort is very slow
- it is very slow when there's 16,000 messages
=> AceEmail: Add more query options

app/logic/Mail/AutoConfig/checkConfig.ts, app/logic/Mail/IMAP/IMAPAccount.ts, app/logic/Mail/JSON/JSONMailAccount.ts, app/logic/Mail/SQL/SQLMailAccount.ts
**Problems**
1. IMAP logs out of OAuth2 in `verifylogin()` thus OAuth2 is `undefined` when verifying for SMTP
2. OAuth2 config is not set in the constructor or login for IMAP login
**Error**
```
SetupMail.svelte:216 Error: Google Mail  SMTP: Need OAuth2 login from IMAP
at assert (util.ts:4:11)
at SMTPAccount.getTransportOptions (SMTPAccount.ts:27:7)
at SMTPAccount.verifyLogin (SMTPAccount.ts:100:61)
at checkConfig (checkConfig.ts:16:29)
at async CheckConfig.svelte:19:3
```
I've added the code for setting the config for IMAP but I'm not sure about the fix for SMTP verify login because I understand we need to logout in case SMTP is not successful.
=> IMAP/SMTP: Set OAuth2 when logging in and verifying login

app/logic/Mail/JSON/JSONEMail.ts
- `emailJSON.tags` is an array of strings, not an array of `{ name: string }` 
- `readTag()` now just reads the param directly instead of access `tag.name`
=> JSON: Mail: Tags: Fix reading

app/logic/Calendar/ActiveSync/ActiveSyncCalendar.ts, app/logic/Contacts/ActiveSync/ActiveSyncAddressbook.ts, app/logic/Mail/ActiveSync/ActiveSyncFolder.ts
`makeSyncRequest` fails to wait for its callback to complete. In the case of calendar and contacts, this means that it saves the new sync key without checking that the callback was successful. In the case of email, this means that new messages don't get added to the folder correctly.
=> Fix race condition in makeSyncRequest

app/logic/Mail/JSON/JSONMailAccount.ts
I missed the `?` when I adding the outgoingID and workspaceID to JSONMailAccount.
```
SetupMail.svelte:216 TypeError: Cannot read properties of null (reading 'id')
at JSONMailAccount.save (JSONMailAccount.ts:25:43)
at _AceMailAccount.save (AceMailAccount.ts:26:32)
at AceMailStorage.saveAccount (AceMailStorage.ts:11:26)
at EWSAccount.save (MailAccount.ts:95:25)
at saveConfig (saveConfig.ts:35:16)
at saveAndInitConfig (saveConfig.ts:14:9)
at onSave (SetupMail.svelte:233:11)
at onContinue (SetupMail.svelte:183:13)
```
=> JSON: MailAccount: Values maybe null

app/logic/Mail/AceBase/AceMailAccount.ts
- AceMailAccount.read() throws `Account reference ID doesn't match saved account ID` because it relies the account.id to read the account and it is not set by JSONMailAccount
- doing `acc.id ??= accID` before the query doesn't work because acc.id is never null and it is set when the mail account is created by the constructor
=> AceMailAccount: Set outgoing account.id

app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Mail/OWA/OWAFolder.ts
Unlike ActiveSync and EWS, where data is transferred using XML, and therefore is stringly typed, OWA uses JSON, and properties actually have useful types. Unfortunately when porting EWS code I didn't always remember this. As well as the case of #278 where only 50 messages can be downloaded, I found a second instance in calendar code, which would prevent it from reading the alarm status of any event.
=> Fix usage of boolean types in OWA code #278

app/logic/Abstract/Account.ts
- I think it's reusing the same `acc.id` becuase it doesn't check the `acc.id` of outgoing accounts because it doesn't get added by `getAllAccounts()`
=> Setup: Check outgoing acc.id also

app/frontend/Shared/FastList.svelte
- The observer was registered before the component mounted thus it was cleared when the component mounted which caused the UI to not update
=> FastList: Register observer after component loads - fixes #289

e2/electron-builder.yml
- Our build for mac was not set to universal
- `target: default` is mandatory
- This was the reason for the slow startup on MacOS
- https://github.com/mustang-im/mustang/actions/runs/12248650829/job/34168650435#step:11:568
=> Build: Mac Universal build with ARM and x86 binaries

e2/electron-builder.yml
- It was using the same prebuilds for both architectures
- https://github.com/mustang-im/mustang/actions/runs/12267607351/job/34228010683#step:11:566
Before
```
skipped dependencies rebuild  reason=npmRebuild is set to false
• packaging       platform=darwin arch=x64 electron=32.2.7 appOutDir=dist/mac-universal-x64-temp
• downloading     url=https://github.com/electron/electron/releases/download/v32.2.7/electron-v32.2.7-darwin-x64.zip size=104 MB parts=8
• downloaded      url=https://github.com/electron/electron/releases/download/v32.2.7/electron-v32.2.7-darwin-x64.zip duration=1.662s
• skipped dependencies rebuild  reason=npmRebuild is set to false
• packaging       platform=darwin arch=arm64 electron=32.2.7 appOutDir=dist/mac-universal-arm64-temp
```
Now it gets the prebuild for each …
=> Build: npm rebuild for prebuilds

.github/workflows/installer-linux-parula.yml, .github/workflows/installer-linux.yml, .github/workflows/installer-mac-parula.yml, .github/workflows/installer-mac.yml, .github/workflows/installer-windows-parula.yml, .github/workflows/installer-windows.yml, e2/electron.vite.config.ts, e2/package.json
- Vite was not generating a source map because it was not configured in electron vite
=> Build: Generate and upload source map for Sentry

app/logic/Mail/ActiveSync/ActiveSyncEMail.ts, app/logic/Mail/EWS/EWSEMail.ts, app/logic/Mail/OWA/OWAEMail.ts
In the case of EWS and OWA, this only works for invitations.
In the case of ActiveSync, this doesn't provide complete data.
=> Calendar: Don't try to load iTIP data through Exchange APIs #268

app/logic/Auth/OAuth2Window.ts, e2/src/main/index.ts
- Sends IPC message to the main process to close the window from there
=> OAuth2Window: Close window from main process #210

backend/backend.ts, e2/src/main/index.ts
IMAP connections won't be closed automatically though, so either they need to be tracked and shut down by the backend or the front end should use an unload handler to close any persistent connections.
=> Allow the backend to be restarted on the Mac #317

app/frontend/Shared/ContextMenu.ts, app/frontend/Shared/WebView.svelte
- Menu Item constructor takes a string for roles or a function for custom actions
- Copy works now
- Cut and paste actions are implemented but not tested yet
=> Context menu roles for predefined actions

lib/jpc/obj.js, lib/jpc/protocol.test.js
There were some issues here:
- Stanza's client object defines an own `subscribe` function which means that we don't send any properties because we assume observing it will achieve this.
- Stanza's client object contains recursive references to itself.
Thus I have created three commits:
- 8c0729a adds support for objects with recursive references, although I'm not entirely sure this works, I should write a test for it and then let you know.
- 6e445e4 requires the `subscribe` function to be on a prototype rather than an own property, although I'm not sure how many Svelte subscribers we actually send over JPC.
- c91bece actually adds support for own method properties on objects.
=> Allow JPC to work with Stanza

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts
`OWAEvent.ts` was using `import { type ResponseType }`, although its values need to be accessible. This doesn't cause a run-time error because the global `ResponseType` object gets used instead, so instead the code just fails silently.
Additionally the import filename was overly long (caused by a move of the file) and this trims the import and groups it with the other imports from the same directory.
The overly long import filename also happens in two other files but in this case that's the only change as they weren't using `import { type ResponseType }`.
=> EWS, OWA, ActS: Fix import of ResponseType

app/logic/Mail/ActiveSync/ActiveSyncEMail.ts
=> ActiveSync: Error messages with account name

app/frontend/Shared/ContextMenu.ts, app/frontend/Shared/WebView.svelte
This reverts commit db21fea03d1045a4137835511ab184c055521ac3.
PR https://github.com/mustang-im/mustang/pull/334 is a regression since SvelteUI menu doesn't have access to "electron menu roles". We would have revert it to how it was before where each menu action is a function and not have any roles.
=> Revert "WebView: Context menu roles for predefined actions (#334)"(#110)

app/frontend/Shared/ContextMenu.ts, app/frontend/Shared/WebView.svelte
- PR #335 fixed the ⁠`RangeError: Maximum call stack size exceeded ⁠` error on the backend, when the `click()` function is called
- Webview methods(`copy()`, `cut()`) should called on `<webview>` instead of `<webview>.contentWindow`
- `shell.shell` is undefined
- What works? All methods supported here https://www.electronjs.org/docs/latest/api/webview-tag#methods e.g. copy(), cut(), paste() and any that doesn't require `webcontents`
- What doesn't work yet? Functions only supported by `webcontents` e.g. copyImageAt(),
=> Webview: Electron context menu fix common actions (#110)

lib/jpc-ws/WSCall.js, lib/jpc-ws/protocol.js, lib/jpc/message.js, lib/jpc/obj.js, lib/jpc/protocol.js, lib/jpc/util.js
There are currently 70 TypeScript errors, including `lib/jpc/obj.js(20,34): error TS2339: Property 'remove' does not exist on type 'Set<any>'.`, which is fixed in the first commit, while the remainder are fixed in the second commit, although you may not like all of the changes TypeScript demands.
=> JPC: Fix TypeScript errors

app/logic/Mail/EMail.ts
`await` has quite high precedence (I'm probably confusing it with `yield` which has very low precedence) so this wasn't doing what I intended; I think this is the clearest way of rewriting it.
=> Fix loadEvent not awaiting properly

app/frontend/Calendar/MonthView.svelte
It's not coded correctly (handlers need to be functions, not snippets) and isn't needed because EventsCell already has a click handler anyway.
=> Remove unneeded nonfunctioning MonthView click handler

app/frontend/Mail/Message/MessageBody.svelte, app/frontend/Shared/WebView.svelte, app/logic/Abstract/Message.ts, app/logic/util/convertHTML.ts
- CSP scope `'unsafe-inline'` is used in all cases because without it inline CSS would not load but `unsafe-inline` is not recommended
- `default-src 'none'` is used in all cases because it's also the fallback directive for scripts, workers and iframes
- It only allows all sources for `img-src` and `style-src` on user request
- For sanitizeHTML I just added an extra condition to add `src` or `href` attribute if it's an image or external css
=>  Mail viewer: Allow external images and css, on user request (#140)

app/frontend/Calendar/CalendarApp.svelte
Currently the calendar always switches to dual view after viewing or editing an event or switching to another app and back. This seems unintentional, particularly after viewing an event. This makes the selected view persists throughout the session.
=> Don't always switch back to dual view

app/frontend/Calendar/CalendarApp.svelte, app/frontend/Calendar/DualView.svelte, app/frontend/Calendar/selected.ts
When clicking on a day in the week or four week view, the view will scroll, sometimes unhelpfully actually past the clicked date. This fixes this by separating the date viewed from the date clicked. (This ends up simplifying the dual view slightly.)
=> Week views should not scroll to clicked date

app/logic/Calendar/ICSProcessor.ts
Unfortunately the old code is valid TypeScript; all it does is declare that `runOn` will always have the value `1`, without actually setting it...
=> Make ICS processor run

app/frontend/Calendar/EditEvent/EditEvent.svelte, app/frontend/Calendar/Invitation.svelte, app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Invitation.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Mail/ActiveSync/ActiveSyncEMail.ts, app/logic/Mail/EWS/EWSEMail.ts, app/logic/Mail/OWA/OWAEMail.ts
This will allow them to be used for participant response status.
=> Responses should be based on ResponseType, not Scheduling

app/frontend/Shared/ContextMenu.ts, app/frontend/Shared/WebView.svelte, backend/WebContents.ts, backend/backend.ts
- We need access to some WebContents in the frontend for some of the context menu actions e.g. `copyImageAt()`
- The change wraps the original WebContents so only the necessary methods are exposed but this is only possible for some of the methods e.g. `win.session.addWordToSpellCheckerDictionary()` is not possible since we'll have to expose the entire `win.session`
- Exposing `win.session` maybe dangerous since there's a methods called `ses.setPreloads(preloads)` which runs node-level scripts
=> Webview: Make necessary only WebContents API available in the frontend (#110)

app/frontend/Shared/ContextMenu.ts, backend/backend.ts
- There's this `Failed to execute 'writeText' on 'Clipboard': Document is not focused` error when using the `navigator.clipboard` so I decided to use the one provided by electron
- The `read()` functions aren't exposed in the renderer process because it poses a security threat where the some code could be used to check what is on the users system clipboard
- So far I haven't found any way to fix `Failed to execute 'writeText' on 'Clipboard': Document is not focused` error to avoid using this method
=> Webview: Context Menu: Copy link and *URLs (#110)

app/logic/Mail/Store/MailZIP.ts, app/test/logic/Mail/Store/MailZIP.test.ts
Sorry if I'm stepping on someone else's toes here.
The actual problem was a missing `await`; see line 25 of `MailZIP.ts`.
However, this isn't enough to fix the test, as it has other problems:
- It's using the wrong filename to open the ZIP file (so the one it does open is still always empty)
- It's trying to compare a Buffer to a Uint8Array
Investigating the filename issue further, I noticed that `writeZip`'s `filename` is just for locking purposes... but `save` passes the wrong filename, so the locking doesn't actually work. I'm not convinced that locking on the filename is ideal; the other alternative is keying your lock and zip maps on the folder, which would at least avoid an extra call to `getFolderZIPFilePath`, but you might want to use `WeakMap`s if you do that.
While debugging I …
=> Fix empty MailZip files #391

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/OWAFolder.ts
- Moved `ParentFolderId` to the correct place
- Switched back to `DistinguishedFolderId`
- Corrected to `BaseFolderId` both there and in the subfolder code
- Also fixed ActiveSync top-level folder creation
=> OWA: Properly create top level folder

lib/util/sanitizeDatatypes.ts
You forgot the `u` flag, and also you probably meant to put the space inside the character class? As such, you're actually removing anything with a following space other than the characters `-.LN_bemprtu{}`.
=> Fix broken sanitisation regex

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
Normally we automatically sync folder deletions from the server but if a full resync is triggered for some reason then we need to clean up any stale folders.
=> ActiveSync: Remove stale folders after a full resync #420

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
This obviously helps in the case of a simultaneous client making a hierarchy change, but could also help in the case where we are the client making the change (although I would still probably want to keep our explicit `listFolders` calls).
=> ActiveSync: React to hierarchy change ping status

app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
Ben's changes in PR #421 broke moving folders. Rather than removing those changes, I now detect the move properly so that we can remember which messages were in the folder.
=> EWS, OWA: Fix for when folders are moved on other clients

app/logic/Mail/OWA/OWACreateItemRequest.ts
This is a port of the change to `EWSCreateItemRequest.ts` in PR #388.
I managed to temporarily switch my TypeScript to 5.4.5 so that it started working again and it picked up this type error.
=> Fix type error after #419 #376

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
I missed these type errors in #426 because I'd forgotten to pull latest `master` first.
The OWA error is because I copied and pasted too much in #424.
The ActiveSync error is because I forgot to import the `Folder` type in #422.
=> OWA, EAS: Fix type errors after #422 #424

app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
This turned out to be harder to test than necessary, because if you have multiple accounts, and try to send messages between them, Mustang will always set the `From` email address to the first account, and changing the identity doesn't change the `From` address...
=> EWS, OWA: Custom sent folder

app/logic/Mail/IMAP/IMAPAccount.ts
After sleeping, the application tried to reestablish a tcp connection and ran into a connection error. The reason for that was that IMAPAccount::reconnect() returned an undefined connection in case of an invalid connection purpose or oAuth2 login failures.
=> Mail: IMAP: Fix undefined connection in reconnect - fixes #371

e2/electron.vite.config.ts, e2/package.json
```
error during build:
[vite-plugin-svelte] [plugin vite-plugin-svelte] ../app/frontend/MainWindow/MainWindow.svelte (31:9): /home/runner/work/mustang/mustang/app/frontend/MainWindow/MainWindow.svelte:31:9 Identifier 'getStartObjects' has already been declared
file: /home/runner/work/mustang/mustang/app/frontend/MainWindow/MainWindow.svelte:31:9
29 |  import { appGlobal } from "../../logic/app";
30 |  import { getStartObjects, loginOnStartup } from "../../logic/WebMail/startup";
31 |  import { getStartObjects, loginOnStartup } from "../../logic/startup";
^
32 |  import { selectedAccount, selectedFolder } from "../Mail/Selected";
33 |  import { getLocalStorage } from "../Util/LocalStorage";
```
- the `vite-plugin-conditional-compile` plugin was never installed and added to the plugins …
=> Build: Run conditionalCompile in e2 also

app/l10n/l10n.ts, app/lingui.config.ts, app/package.json, e2/package.json
- Lingui requires extraction and compilation for it to properly function even for fallback
- FormatJS is the standard library for ICU Message format so I picked that and it also works for as a replacement runtime
- FormatJS as a runtime doesn't require extraction or compilation
- You can now edit and save the translation and hot reload would reflect it immediately without restarting the dev server
- No more `*-compiled.json` is needed
- Better solution than #114
=> Translations: Use FormatJS runtime (#108)

app/logic/Calendar/ICSProcessor.ts, app/logic/Calendar/ICalParser.ts, app/package.json
The parsing part is reasonably straightforward.
=> Remove node-ical module and use simple parser #267

e2/src/main/index.ts
I was able to make `getAccessTokenFromParams` use a regular `fetch` to get its data (and of course the fetch also shows up on the developer tools).
=> Fix CORS request header filtering

app/frontend/Calendar/DisplayEvent.svelte, app/frontend/Calendar/EditEvent/ParticipantsBox.svelte, app/frontend/Calendar/EditEvent/PersonAvailability.svelte, app/frontend/Calendar/EditEvent/PersonResponse.svelte, app/frontend/Shared/PersonAutocomplete/PersonsAutocomplete.svelte, app/logic/Abstract/PersonUID.ts, app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/ICSProcessor.ts, app/logic/Calendar/Invitation.ts, app/logic/Calendar/JSON/JSONEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/Participant.ts, app/logic/Calendar/SQL/SQLEvent.ts, app/logic/Calendar/SQL/createDatabase.ts
This includes the display of the response status of participants.
Or it would, if I could figure out how to view meeting participants in the new UI... they seem to have all disappeared, along with the close button...
Originally I thought creating the subclass was the way to go, but in the end it might have been be better to just add the property to PersonUID in the first place...
=> Create Participant subclass of PersonUID

app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Mail/OWA/OWAAccount.ts
I see you restored `isOnline`!
Creating an event in the correct calendar is still awkward.
- Open Calendar view
- Click `+`
- Select the correct calendar from the picker
- Click `X`
- Click `+`
- Now create the event.
Note that if you don't add a description to the event before turning it into a Teams meeting, you won't see the Teams meeting description, because it's in text, not HTML.
=> OWA: Teams Meetings

app/frontend/MainWindow/WindowHeader.svelte, app/frontend/Util/util.ts, e2/src/main/index.ts
- Add styles for MacOS only
- Move app logo to the right of the traffic light
- Move title closer to the logo
- Remove Mustang Minimize and Close buttons
- Only enable if not Webmail and the OS name is "macintosh"
Haven't tested if it affects other OS builds yet.
=> Mac: Native style title bar (#410)

app/frontend/Shared/Editor/HTMLEditor.svelte, app/package.json
- Set image size to window and add the ability to resize
- You can also align the Image
- The sent result is the same
=> Mail Composer: Set image size to window and add the ability to resize #414

app/logic/Mail/EWS/EWSAccount.ts
(I was confused with the UI and didn't realise that drag-n-drop from the OS file manager is apparently the only working way to insert images. It's my least preferred way of inserting images... Anyway, the password went missing from the EWS account in my configuration for some reason, but I didn't realise that was wrong because the server UI always shows `••••••••` as a placeholder...)
=> Use correct tag when creating attachments to messages #466

e2/src/main/index.ts
- The imported icon was never changed with the correct icon file
- The resources folder indeed is for the `main` and `preload` folder but to continue using that folder we would have to copy the icon to that folder so I just pointed to the file in build folder.
=> Branding: Linux: Use correct icon (#471)

app/frontend/Settings/About/Licenses.svelte, app/frontend/Util/util.ts, e2/electron.vite.config.ts
There were 3 problems that caused this bug:
1. The public assets were never copied to the dist folder because the default is '<root>/public' and in the case of `e2` it is `e2/public` which has no assets in there. I've set it to `../../../app/public`
2. The file was using the `file:///` url instead of HTTP which doesn't tell the browser it is a gzipped file and it needs to unzip it. I've implemented a `fetchGzip()` function for that and it fetches and unzips it. In development these static assets are served through HTTP so that's why there's no issue.
3. The URL is wrong in production when you set `public/attribution.txt.gz` it turn into `<root>/public/attribution.txt.gz` which is not the correct location in production since the static assets are copied to root and there's no public …
=> Build: Open-Source licenses file is not in production build #476

app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/OWA/Request/OWAEventRequests.ts, app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/Contacts/OWA/Request/OWAPersonRequests.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/OWAEMail.ts, app/logic/Mail/OWA/OWAFolder.ts, app/logic/Mail/OWA/Request/OWACreateItemRequest.ts, app/logic/Mail/OWA/Request/OWADeleteItemRequest.ts, app/logic/Mail/OWA/Request/OWAFolderRequests.ts, app/logic/Mail/OWA/Request/OWARequest.ts, app/logic/Mail/OWA/Request/OWASubscribeToNotificationRequest.ts, app/logic/Mail/OWA/Request/OWAUpdateItemRequest.ts
Refactoring only. No functional changes.
* The OWA implementation files are very long, but mostly because of the JSON literal objects that we need to send as requests to the server.
* Move these into separate files in Request/ subdir
* We already have existing `*Request` classes, but:
* They don't have a common superclass
* Adding the parameter in the constructor makes these JSON objects much more difficult to read.
* When the requests are not classes, but inline JSON literal, they are much easier to read. I would like to preserve that
* Therefore, I have decided to put them into functions (not classes). This allows to keep them as literals *with their parameter*.
* Nonethless, a common class for requests would be nice. Plus, the header is very repetitive and can be factored out. Only the …
=> OWA: Move OWA JSON request literals into separate files

app/frontend/MainWindow/WindowHeader.svelte
- Styling to fix button over lap in RTL languages on Mac
=> Mac: WindowHeader: Styling to fix button overlap in RTL languages (#469)

app/l10n/l10n.ts, app/vite.config.ts
`window.global = window;` doesn't work when the file gets included by a test.
=> Polyfill global for frontend

app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/Folder.ts, app/logic/Mail/OWA/OWAFolder.ts
Port of ebdb226.
(Why do we have `AbstractFunction` when we can just use TypeScript's abstract classes?)
=> EWS, OWA: Fix save draft

app/frontend/Shared/Editor/HTMLEditor.svelte, app/frontend/Shared/Editor/ParagraphNewLine.ts
- Adds a `<br>` when there's no `<br>`
- Splits paragraph into 2 paragraphs when there's already a `<br>`
- Only happens in first level `<p>` so `<li><p></li>` is not affected and still has the default behavior
=> Mail Composer: Newline vs. paragraph (#35)

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/ActiveSync/ActiveSyncEMail.ts, app/logic/Mail/ActiveSync/ActiveSyncFolder.ts, app/logic/Mail/ActiveSync/WBXML.ts
The alternative would be to directly support 16.1 as a protocol version, which would mean having to check all of the APIs we currently use to see if they work differently in 16.1
[Sync Command Request](https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-asemail/a8602ea5-a3f3-4426-83b5-a8d5315a953d)
=> ActiveSync: Save draft if 16.1 available

app/logic/Calendar/OWA/OWAEvent.ts
It seems to have been accidentally lost due to a merge conflict when you rebased #455.
=> Restore code to detect online meetings created by other clients

app/frontend/Settings/About/About.svelte, app/frontend/Settings/Mail/Read.svelte, app/l10n/T.svelte, app/l10n/extractor/svelteExtract.ts, app/l10n/extractor/utils.ts
- There were many problems with the <T> component when extracting string from it since it doesn't know what values are there at compile time.
- I replaced all instances where <T> is used for translation with $t.
=> L10n: Use <T> component only for interpolation (#518)

app/logic/Calendar/Event.ts
Also removes some unneeded `.getTime()` calls when cloning `Date`s.
=> Make occurrences default to the time zone of their master

app/frontend/Mail/Composer/MailAutocomplete.svelte, app/frontend/Mail/Composer/MailComposer.svelte, app/frontend/Shared/PersonAutocomplete/PersonEntry.svelte
- There were 2 issues I found that caused the UI to freeze, the `person` prop was access before mount is always `undefined` and in the inner components the slots took a `person` prop instead of a `personUID` but `personUID` was the prop passed only in MailComposer, in Display even it uses a `person` also
=> Mail composer: Use props properly in slots (#489)

app/logic/Calendar/ActiveSync/ActiveSyncCalendar.ts, app/logic/Calendar/Calendar.ts, app/logic/Calendar/EWS/EWSCalendar.ts, app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Calendar/OWA/Request/OWAGetUserAvailabilityRequest.ts, app/logic/Mail/ActiveSync/ActiveSyncError.ts, app/logic/Mail/ActiveSync/WBXML.ts, app/logic/Mail/EWS/EWSAccount.ts
Works from the console at least.
Note that EWS and OWA return one availability entry for each event within the time frame, while ActiveSync returns half hour availability entries for the entire time frame which are marked free only if no busy event overlaps the given half hour.
=> Calendar: Free/Busy: EWS, OWA, ActiveSync

app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts
Exchange Online EWS doesn't like it any more.
Obviously I didn't want to break any of the back end for handling recurring events, but I basically had to rewrite parts of the UI in order to get it into a position where I could test the change to make sure that, were the UI to work, the back end would actually do the right thing.
I was also disappointed to find that the UI to set the end date of a recurring event was never restored.
=> Don't try to unset the recurrence of an instance

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/JSON/JSONEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts
- Fixed cases where an event wasn't getting correctly marked as an exception
- Tried to fix `JSONEvent` (untested)
While I was there I noticed that there's no support for recurring masters that were turned back into single events from a different client. This is possible in Lightning and in older versions of Outlook Web Access but they removed the UI from Exchange Online.
=> Fix some more recurrenceCase cases in the backend

app/frontend/Mail/Tag/TagAdd.svelte
- Validate the tag name before dispatching an `Add` event
- The component was allowing a tag with no tag name to be added
=> Mail: Tags: Validate tag name before adding (#538)

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/OWA/OWAEvent.ts
Also fix Office 365 to save timezones correctly (regression from #455).
Plus fix EWS to read the timezone correctly (bug in #517).
=> EWS, OWA, ActiveSync: Save timezone

app/frontend/Calendar/DisplayEvent/Invitation.svelte, app/frontend/Calendar/DisplayEvent/MoreBubble.svelte, app/frontend/Calendar/DisplayEvent/ParticipantsDisplay.svelte, app/frontend/Calendar/EditEvent/TitleBox.svelte, app/frontend/Contacts/PersonAutocomplete/PersonPopup.svelte, app/frontend/Contacts/PersonDetails.svelte, app/frontend/Mail/Composer/MailComposer.svelte, app/frontend/Mail/Search/RulesFromSearchUI.svelte, app/frontend/Mail/Search/SavedSearchUI.svelte, app/frontend/Settings/Mail/Manual/ManualConfigURL.svelte, app/frontend/Setup/Shared/Footer.svelte
- Replaced instances of `font-size` in CSS rules with classes: `font-smallest`, `font-small`, `font-normal`
- Instances where components export a `classes` prop and select the correct element are replaced
- Instances where the CSS rule is in a tag select are replaced
- Instances where there's a `!important` is still not replaced
=> UI: Change font sizes into CSS classes - Pass 2 (#556)

app/TODO.md, app/logic/Calendar/SQL/SQLCalendar.ts, app/logic/Calendar/SQL/createDatabase.ts, app/logic/Chat/SQL/SQLChatAccount.ts, app/logic/Chat/SQL/SQLChatMessage.ts, app/logic/Chat/SQL/createDatabase.ts, app/logic/Contacts/SQL/SQLAddressbook.ts, app/logic/Contacts/SQL/createDatabase.ts, app/logic/Mail/SQL/Account/SQLAccount.ts, app/logic/Mail/SQL/Account/createDatabase.ts, app/logic/Mail/SQL/SQLEMail.ts, app/logic/Mail/SQL/SQLFolder.ts, app/logic/Mail/SQL/SQLMailAccount.ts, app/logic/Mail/SQL/createDatabase.ts, app/logic/Meet/SQL/SQLMeetAccount.ts, app/logic/Meet/SQL/createDatabase.ts
* Add `json` column to most tables, for supplemental properties. This allows to add message-specific additional data, e.g. from addons or for calendar, without changing the DB schema.
* Move email.scheduling into the JSON, given that it's used only for emails that contain invitations
* Move folder.uidvalidity into JSON, given that it's needed only for IMAP folders.
* Keep syncState as separate column, not in JSON, given that it's needed for most protocols, and will be written often.
* Add `meet.call` table, for a call log
=> SQL: Add json column to most tables, for supplemental properties

app/logic/Abstract/Account.ts, app/logic/Calendar/ActiveSync/ActiveSyncCalendar.ts, app/logic/Calendar/EWS/EWSCalendar.ts, app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Calendar/SQL/SQLCalendar.ts, app/logic/Chat/SQL/SQLChatAccount.ts, app/logic/Contacts/ActiveSync/ActiveSyncAddressbook.ts, app/logic/Contacts/EWS/EWSAddressbook.ts, app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/Contacts/SQL/SQLAddressbook.ts, app/logic/Mail/AccountsList/MailAccounts.ts, app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/SQL/Account/SQLAccount.ts, app/logic/Mail/SQL/Account/createDatabase.ts, app/logic/Mail/SQL/SQLMailAccount.ts, app/logic/Meet/SQL/SQLMeetAccount.ts, app/logic/startup.ts
* Add `Account.mainAccount` and `Account.dependentAccounts()`
* Persist it to DB and restore it after load
* Use it for addresssbook and calendar to email account in Exchange protocols
* TODO: SMTP to IMAP
=> Account: Add mainAccount and dependent accounts - fixes #155

app/logic/Calendar/Invitation.ts
As requested in #570.
I've finally figured out that what you call invitations everyone else calls meetings. I find that really confusing, because to me invitations are the emails with an iCal method of REQUEST...
=> Clarify response types

app/frontend/Settings/Mail/Manual/ManualConfig.svelte, app/logic/Abstract/Account.ts, app/logic/Calendar/Calendar.ts, app/logic/Chat/ChatAccount.ts, app/logic/Contacts/Addressbook.ts, app/logic/Mail/AutoConfig/saveConfig.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/MailAccount.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Meet/MeetAccount.ts
As mentioned in #574:
- accounts are trying to save their dependent accounts first, which doesn't work
- EWS and OWA accounts need a "light" `verifyLogin` which doesn't try to create dependent accounts
=> Fix various constraint failures during account setup

mobile/backend/vite.config.ts
**Errors**
1. Our code is ESM and needs to be compiled to ESM
2. Vite lib mode targets to browser
**Notes**
- I remembered that we changed all modules to ESM so the build needs to target ESM otherwise there would be an error.
- I tried the `cjs` format but I kept getting errors. Was there a reason for setting the build to CJS?
- Another error, was that vite in `lib` mode only targets browser so it was bundling for the browser. [link](https://github.com/vitejs/vite/issues/8910#issuecomment-1174779427)
- I tried another fix by removing the `browser` from `resolve.mainFields`. [link](https://github.com/vitejs/vite/issues/8910#issuecomment-2128107137)
- So the fix that worked for me was setting `build.ssr` to true and` ssr: { noExternal: true }`. …
=> Mobile: Backend: Vite config target for Node.js & ESM

app/frontend/Calendar/EditEvent/DialogHeader.svelte, app/frontend/Calendar/EditEvent/EditEvent.svelte, app/frontend/Calendar/EditEvent/InvitationResponseButtons.svelte, app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/Invitation/OutgoingInvitation.ts, app/logic/Calendar/OWA/OWAEvent.ts
I am confused as to why `EditEvent` has a check, then an `<hbox>`, then an `InvitationResponseButtons`, which itself then contains an `<hbox>` and a check, but I wasn't sure which could be removed.
=> Create explicit property to check for incoming meetings

mobile/android/app/src/main/AndroidManifest.xml, mobile/backend/package-deploy.json, mobile/backend/package.json, mobile/backend/vite.config.ts
- Make capacitor-nodejs start an ESM module
- Allow clear text traffic for now to connect the frontend to the backend
- Copy the backend files to the `webDir` so it's copied to the android build files also and it prevents it from getting deleted by an overwrite
- Based on #584
=> Mobile Backend: Make capacitor-nodejs start an ESM module (#583)

app/frontend/Calendar/EditEvent/DialogHeader.svelte, app/frontend/Calendar/EditEvent/EditEvent.svelte, app/frontend/Calendar/EditEvent/RepeatBox.svelte, app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/OWA/Request/OWAEventRequests.ts, app/logic/Calendar/RecurrenceRule.ts
- After deleting all other instances of a series, deleting the last instance deletes the series
- If editing the first instance of a series, provides button to delete entire series
- If editing an instance in the middle of a series, provides button to delete remainder of series
- If editing the first instance of a series, allows recurring master to be replaced with current event
- If editing an instance in the middle of a series, allows a new series to be started from this point (truncates old series)
Notes:
- When replacing part or all of a series, you must specify the recurrence again, as the start date may have changed, invalidating the previous recurrence
- For some reason, after converting a series back to a single event, the UI gets confused and needs a restart to be able to convert …
=> Allow future events of a series to be changed #478

app/frontend/Calendar/DayView/WeekView.svelte
- Calendar: WeekView: Only use start if it's not undefined
- This seems to be the bug where when you switch apps the variable binding happens after mount so it's intially `undefined`
=> Calendar: WeekView: Only use start if it's not undefined (#588)

app/frontend/Meet/View/Gallery.svelte
- The inner name label element also had a participant class so the `scroll-snap-align` was also being applied to that.
- Even with this fixed the there's still a little half video at the bottom.
- Because the `clientWidth` and `clientHeight` of the gallery includes the scroll it causes the size to be miscalculated.
- There's a way to fix but it's not ideal you would need to get the `clientWidth` and `clientHeight` of the `<Scroll>` component.
=> Meet: Gallery: Scroll snap into top of video (#598)

app/frontend/Calendar/EditEvent/DateInput.svelte, app/frontend/Calendar/EditEvent/DialogHeader.svelte, app/frontend/Calendar/EditEvent/EditEvent.svelte, app/frontend/Calendar/EditEvent/RepeatBox.svelte, app/frontend/Calendar/EditEvent/TimeBox.svelte, app/logic/Calendar/Event.ts, app/logic/Calendar/RecurrenceRule.ts
The repeat box now shows automatically for unedited instances allowing you to easily change all future events. Also fixes #591 and fixes #592.
Other bugs that were fixed:
- Changing event duration needs to reset exceptions and removes exclusions
- Repeat box wasn't noticing the change to the event's start date
- Repeat box was erroneously mutating the recurrence rule's weekdays
- Save all icon wasn't appearing correctly
- Code in `makeExclusions` was broken
=> Followup to changing future events of a series

app/frontend/Calendar/DayView/WeekView.svelte, app/frontend/MainWindow/MainWindow.svelte
- The `sidebar` variable was switching too quickly
- debouncing setting the variable prevents it from mounting and destroying too quickly which causes svelte stores binded to those components to be set to `undefined`.
=> MainWindow: Debounce sidebar variable (#588)

app/logic/Calendar/Event.ts
Certain actions can cause the dialog header element to refresh, which will then attempt to restart editing of the event.
=> Don't restart editing an event when the editor is refeshed

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts
When this code was originally written, there was no alarm UI, so the code got copied without being tested.
The main bug is that Lightning uses a (negative) offset in seconds for its reminder, but Mustang works with JavaScript dates, so there's a 1000× discrepancy.
EWS and OWA also require special handling for incoming invitations. (ActiveSync requires you not to have special handling.)
=> EWS, OWA, ActiveSync: Fix alarm handling

app/frontend/Calendar/EditEvent/DurationUnit.svelte, app/frontend/Calendar/EditEvent/ReminderBox.svelte
The duration in unit was not calling the correct function to notify the duration unit widget of the change.
Furthermore, there was an update loop that prevented you from change the duration after changing the duration unit.
Additionally the `min={0}` was not actually achievable.
This meant that the only reminders possible were 5 minutes, 1 hour and 1 day.
I also checked to ensure that the event duration UI was unaffected.
=> Calendar: Edit: Reminder: Fix to allow editing it

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, backend/backend.ts
I had to increase the timeout otherwise `ky` will just abort the request. (I tried 20s but that was too low.)
=> Provide useful message if ActiveSync server sends Retry-After header

app/logic/Auth/OAuth2.ts, app/logic/Auth/UI/OAuth2Embed.ts
- The port was still 5455 in dev mode, even though the correct port is 5453
- That means Gmail logins always got stuck after the consent screen because the authDoneURL didn't match
- Added extra authDoneURL logging for debugging in production if it still happens in production
=> OAuth2: Set the correct port for authDoneURL (#581)

app/frontend/Calendar/EditEvent/TimeBox.svelte, app/logic/Calendar/Event.ts
As per RFC5545 section 3.6.1 I also disable the time zone for all day events. I also set the minimum for the end date picker for convenience.
=> Align with iCal for the end time of all day events

app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/OWA/Request/OWAUpdateOccurrenceRequest.ts, app/logic/Mail/EWS/Request/EWSUpdateItemRequest.ts, app/logic/Mail/OWA/Request/OWAUpdateItemRequest.ts
Current behaviour:
- ActiveSync
- Office 365
- Other OWA
- EWS
The problem is that the spec says that the time zone comes after the time when creating events but before it when updating events.
This change attempts to address the issue by reversing the order in which fields are updated for EWS and other OWA.
=> EWS, OWA: Fix editing timezone

app/logic/Calendar/ICal/ICalGenerator.ts, app/logic/Calendar/ICal/ICalToEvent.ts
DTSTART/DTEND has three formats:
- for all day events, VALUE=DATE with just a YYYYmmdd date
- for events in UTC, VALUE=DATE-TIME with a YYYYmmddThhmmssZ timestamp
- otherwise, VALUE=DATETIME and TZID=zone with a YYYYmmddThhmmss time
As this was getting complicated, I rewrote the code to make it clearer.
We were also parsing UTC times incorrectly, giving them a local time zone; this PR also fixes that.
=> Fix parsing and generating of iCal timezone

app/frontend/Calendar/DisplayEvent/DisplayEvent.svelte, app/frontend/Calendar/EditEvent/RepeatBox.svelte, app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/RecurrenceRule.test.ts, app/logic/Calendar/RecurrenceRule.ts
You remember why I had `class RecurrenceRule extends Readonly<RecurrenceInit>`? Well, this is why.
=> Calendar: Recurrence: Rename more startDate into seriesStartTime

app/frontend/Shared/FastList.svelte
- the wheel event seems to be triggering a lot per second which caused the scrolling to be too fast, however, the deltaY was only 1 or 2
- when you use a scroll wheel there's less events triggered per second but the deltaY was much more
- I'm proposing throttling onWheel callback to prevent scrolling too fast for trackpads but also we need to adjust the scroll based on the deltaY for scroll wheels otherwise it would be too slow for scroll wheels
- this will be a little different since we're not scrolling 3 items on each scroll
=> FastList: Scroll speed normalized (#361)

app/logic/Calendar/Event.ts
`setRecurrenceRule` wants to be able to work while adding a rule to an event, which means that the recurrence case hasn't been set, which means we can't clear the exceptions yet. So we have to set a temporary flag to know whether we should clear exceptions.
=> Make changing the recurrence rule clear exceptions again

app/logic/Mail/MailAccount.ts
When `newEMailFrom` was originally created, its `folder` was set to Drafts, although drafts were not actually supported at the time. Additionally, sent messages were always saved in the Sent folder.
Draft processing has since been added, but this now explicitly finds the Drafts folder, as the email's folder is now used as the desired Sent folder.
This means that `newEMailFrom` needs to use the Sent folder by default.
=> New outgoing messages should default to saving in the Sent folder

app/logic/util/convertHTML.ts
If either the text or HTML of an email is `null` (which is a legal value), this code crashes as part of trying to create the MIME.
=> Safely fix newlines, since the value could be null

app/logic/Calendar/Event.ts, app/logic/Calendar/Invitation/OutgoingInvitation.ts
- Don't send invitations when changing, say, the reminder
- If only adding/removing participants, only send them invitations/cancellations
- But if major event details change, send to all participants
=> Invitation: Send only when specifically needed

app/logic/Calendar/Event.ts, app/logic/Calendar/RecurrenceColl.ts
`mapToCollection` has a problem, and that is that it assumes that the mapping function is idempotent, i.e. it always returns the same value each time.
This is not true with our current `mapToEvents` function, except in the edge case where you only create and delete recurring events (which does work on current code).
Now there may be another way to achieve this which allows a dynamic mapping function, but I chose to go the other way and make the mapping function idempotent.
To this end, the `instances` collection of the event should contain itself if it's a single event or an exception otherwise it should contain its occurrences.
While I was there I noticed that changing a recurring event to a single event didn't remove its occurrences (because clearExceptions regenerates them) so I …
=> Update UI after simple event is deleted or made recurring

app/frontend/Util/util.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/ICal/ICalEMailProcessor.ts, app/logic/Calendar/ICal/ICalGenerator.ts, app/logic/Calendar/ICal/ICalToEvent.ts
* Read HTML description from iCal
* Save HTML description to iCal
In 3 formats:
* [RFC 2445 4.2.1](https://datatracker.ietf.org/doc/html/rfc2445#section-4.2.1), 4.2, [RFC 5545 3.2.1](https://www.rfc-editor.org/rfc/rfc5545#section-3.2.1) ([iCal.org descr](https://icalendar.org/iCalendar-RFC-5545/3-2-1-alternate-text-representation.html)) and [Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1607834) format: `DESCRIPTION` property with parameter `ALTREP` with `data:text/html` URL as value of the parameter
* [RFC 9073 6.5](https://www.rfc-editor.org/rfc/rfc9073.html#name-styled-description) format: `STYLED-DESCRIPTION` property with parameter `FMTTYPE="text/html"` and HTML as value of the property
* Outlook format: `X-ALT-DESC` property with parameter `FMTTYPE="text/html"` and HTML …
=> Calendar: HTML descriptions

app/frontend/Calendar/DisplayEvent/Invitation.svelte, app/logic/Abstract/PersonUID.ts, app/logic/Calendar/ActiveSync/ActiveSyncIncomingInvitation.ts, app/logic/Calendar/EWS/EWSIncomingInvitation.ts, app/logic/Calendar/Event.ts, app/logic/Calendar/ICal/ICalEMailProcessor.ts, app/logic/Calendar/ICal/ICalToEvent.ts, app/logic/Calendar/Invitation/IncomingInvitation.ts, app/logic/Calendar/OWA/OWAIncomingInvitation.ts, app/logic/Calendar/Participant.ts, app/logic/Calendar/SQL/SQLEvent.ts
When we receive:
* A reply from a participant to an meeting that we organize
* A cancellation from an organizer
we should automatically update the information in the event in our calendar, so that the event has the most up-to-date status about all participants that responded, and can show that an event that we were previously invited to was now cancelled.
The processing should happen
a) immediately once we received the email
b) when the user reads the email
=> Invitation: Auto-process replies and cancellations #619

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSCalendar.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/OWA/Request/OWAEventRequests.ts
The organiser sometimes show up in the attendee list but even then its status is not reliable so this ensures the organiser is displayed with the correct status.
=> Calendar: ActiveSync, EWS, OWA: Show correct organiser status

app/frontend/Calendar/DisplayEvent/DisplayEvent.svelte, app/frontend/Calendar/EditEvent/DialogHeader.svelte, app/frontend/Calendar/EditEvent/EditEvent.svelte, app/frontend/Calendar/EditEvent/RadioGroup.svelte, app/frontend/Calendar/EditEvent/RepeatBox.svelte, app/frontend/Calendar/EditEvent/TimeBox.svelte, app/logic/Calendar/Event.ts, app/logic/Calendar/RecurrenceRule.ts
The old code was saving the changes in local variables in the UI, and then pushed it to the event on save. There are at least 2 problems with that:
1. It's against our general idea to a) apply changes directly on the object and b) that changes show up immediately in the rest of the app, whenever possible
2. More importantly, the `let foo =` in RepeatBox.svelte meant that the calendar edit dialog in the sidebar would not refresh and show the values of the previously selected event. This is because `let foo =` is run only when the component is instantiated. Later changes to the properties do *not* re-run that code, and therefore, the variables were not updated to the new data. To fix that, we need to use `$:`, which re-runs the line whenever one of the values changes (as far as Svelte …
=> Calendar: Edit: Recurrence

app/frontend/Calendar/EditEvent/DialogHeader.svelte, app/logic/Calendar/Event.ts
Prior to #725, a recurring master's rule didn't get updated until you clicked save. This meant that `onChangeRemainder` would automatically pick up the new rule as it saved the new series, while `Event.seriesStatus` and `Event.truncateRecurrence` were both relying on the master's rule being unedited. `onChangeRemainder` now has to clone the rule, if it wasn't turned off, `Event.seriesStatus` has to now check the unedited state, while for `Event.truncateRecurrence` I just cancel editing to simplify matters. Furthermore, `Event.seriesStatus` suffered the double whammy of an unedited instance not being able to find itself in its master's instance list, presumably due to the recent more dynamic instance generation changes.
=> Fix bugs handling remainder of series #725 #729

app/logic/Mail/ActiveSync/WBXML.ts
I think ActiveSync 16.1 will send us `AirSyncBase:Location` instead of `email:Location` tags for invitation emails; we don't actually read that but it logs a console warning. We also get `email2:CalendarType` tags if the invitation is for a recurring event.
When adding the `email2:IsDraft` and `email2:Bcc` tags I failed to notice that there's a gap in the numbering of the `email2` code page. This caused us to mark all messages as draft on ActiveSync 16.1 servers.
=> Fix WBXML tags for ActiveSync 16.1 #762

app/logic/Calendar/Event.ts
#725 changed `RecurrenceRule.getOccurrencesByDate` to return all of the cached occurrences, not just filtered down to the desired date.
Unfortunately `Event.getOccurenceByDate` (added in #663) was relying on `generateRecurrences` to only generate the exact number of occurrences.
(Because #663 removed the 1-1 correspondence between recurrence rule occurrences and instances, I don't have any better way of finding the right instance.)
=> Fix getOccurrenceByDate might return the wrong occurence #725

app/logic/Calendar/OWA/OWACalendar.ts, app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/util/RunOnce.ts
In particular, `listContacts` and `listEvents` are relatively slow on OWA, so we don't want to accidentally run them when they're already running.
=> Prevent slow functions from being reentered

app/logic/Calendar/Invitation/IncomingInvitation.ts, app/logic/Calendar/OWA/OWAIncomingInvitation.ts
In particular, this means that if an attendee changes their attendance of a single instance of a recurring meeting to which they were invited, this will now correctly update a local calendar.
=> Improve support of invitations of single occurrences

app/logic/Calendar/ActiveSync/ActiveSyncEvent.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts, app/logic/Calendar/OWA/Request/OWAEventRequests.ts
This used to fail because instances are locally generated and so don't have a server or item id.
I'm going to have to look up how to support this in ActiveSync 14.0 as that doesn't support the instance id.
When I tested, I couldn't get the user's calendar to show the new status, although Exchange had sent the email and the organiser's calendar showed their status, but maybe that was just me.
=> EWS, OWA, ActiveSync: Accept an instance of a recurring meeting

app/logic/Mail/AutoConfig/saveConfig.ts
The user has manually configured this, so don't overwrite the values that the user has set.
=> Setup: Mail: Manual: Avoid to overwrite the password #309

app/logic/Calendar/Event.ts, app/logic/Calendar/Invitation/IncomingInvitation.ts
When you invite a participant to a recurring meeting but they have a custom response to a single occurrence, this does not currently get processed properly. There are two problems:
1. The instance turns into an exception, but this means it needs to be added explicitly to its parent calendar's event list.
2. The instance has a shallow copy of the list of participants, which allows it to show the correct master response (if the participant previously replied to the entire series), but we need to deep clone the list before modifying it. (This is not normally a problem because we don't normally modify participants in-place.)
I don't know why `saveLocally` was saving the parent event; creating an exception has no effect on the parent.
=> Properly handle acceptance of occurrence of series

app/logic/Calendar/Invitation/OutgoingInvitation.ts
I'm not exactly sure how I triggered this but I was editing a meeting and I got an error saying that my invitation message had no recipient.
Since i was there I thought there was no point sending a cancellation to a declined attendee.
(Strictly speaking this is a regression from eef7737 as the previous code sent separate messages for each participants therefore guaranteeing that if there were no relevant participants then no messages were sent.)
=> Don't send invitations/cancellations to empty participant list

app/frontend/Setup/Mail/DisplayConfig.svelte, app/frontend/Setup/Mail/DisplayConfigServer.svelte, app/frontend/Setup/Mail/Instructions.svelte, app/frontend/Setup/Mail/SetupMail.svelte, app/logic/Abstract/TCPAccount.ts, app/logic/Files/WebDAV/WebDAVAccount.ts, app/logic/Mail/AccountsList/MailAccounts.ts, app/logic/Mail/AutoConfig/SetupInfo.ts, app/logic/Mail/AutoConfig/configInfo.ts, app/logic/Mail/AutoConfig/localConfig.ts, app/logic/Mail/AutoConfig/readConfig.ts, app/logic/Mail/AutoConfig/saveConfig.ts, app/logic/Mail/MailAccount.ts, app/logic/util/collections.ts
* AutoConfig: Read CalDAV, CardDAV, WebDAV into from the autoconfig XML file
* Setup UI: Show the found config, to allow the user to verify the hostnames
* Setup logic: Create the calendar, addressbook and file share accounts, together with the email account
* Disabled for now, until #778 lands
=> Setup: Autoconfig for CalDAV, CardDAV, WebDAV

app/logic/Contacts/OWA/OWAAddressbook.ts, app/logic/Mail/EWS/EWSAccount.ts, app/logic/Mail/OWA/OWAAccount.ts
Although this works for OWA, OWA wasn't designed to sync, which means that the refresh is really slow, and could even end up running multiple times in parallel...
=> EWS, OWA: Refresh contacts and calendars #771

app/frontend/Settings/Mail/Manual/ManualConfigURL.svelte, app/frontend/Setup/Mail/SetupMail.svelte
PR #815 changed the way OWA full page login works, which broke manual setup.
Manual setup also didn't work properly with EWS accounts, and this also improves that.
The changes in `ManualConfigURL` were ported from `ManualConfigHostServer`, while the change in `SetupMail` was ported from line 173 as I assume manual setup has no instructions.
=> Allow manual setup of OWA accounts with full page login again

app/frontend/Calendar/EditEvent/RepeatBox.svelte, app/logic/Calendar/Event.ts
- Also update the rule if the user changes the event's duration
- After updating the rule, use the new rule to update the UI, rather than validating the rule in the UI
=> Move recurrence rule validation into `newRecurrenceRule` #802

app/logic/Auth/OWAAuth.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/Request/OWAFolderRequests.ts, backend/owa.ts
As requested in PR #815.
Note that `callOWA` uses `fetchJSON` which checks for the `X-OWA-CANARY` cookie before hitting the network.
=> OWA: Stop using sessiondata.ashx

.github/workflows/installer-android.yml, mobile/backend/prebuild.sh, mobile/docs/build.md, mobile/package.json
- Many of the env variables were set in the CI script so when you did a local build those env variables were not set
- Moved all the env variables to be included in the npm and sh scripts
=> Android build: Move env from workflow to scripts

app/frontend/Calendar/DayView/EventsBlockCell.svelte, app/frontend/Calendar/DayView/TimeDayRow.svelte, app/frontend/Calendar/DayView/WeekView.svelte, app/frontend/Calendar/MonthView/MonthView.svelte
As mentioned in #842, if I have 11870 events (recurring instances) then that results in 2991240 subscriptions by `filterObservable` and the Calendar first time open is three seconds; with these extra filters, this reduces to 110972 subscriptions and the Calendar first time open time reduces to under half a second.
=> Pre-filter event collections in the day and month views #842

lib/jpc/obj.js
Found by `tsc --noUnusedLocals`.
=> Remove duplicate call to getOrCreateIDForLocalObject #841

app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Calendar/OWA/OWAEvent.ts
Found by `tsc --noUnusedLocals`.
=> EWS, OWA: Actually use local weekdays varible in `saveRule` #841

app/logic/Mail/Folder.ts
Found by `tsc --strictNullChecks`.
Now all we need is a way to move them back to the top level...
=> Fix moving top level folders into folders #841

app/tsconfig.json, lib/jpc/obj.js
The type annotations in JPC tell TypeScript what type of object the function will actually be run against, so that it can type check uses of `this`.
=> Turn on noImplicitThis TypeScript type checking #841

app/logic/Auth/OWAAuth.ts, app/logic/Calendar/EWS/EWSEvent.ts, app/logic/Mail/ActiveSync/ActiveSyncAccount.ts, app/logic/Mail/ActiveSync/ActiveSyncFolder.ts, app/logic/Mail/EWS/EWSFolder.ts, app/logic/Mail/Folder.ts, app/logic/Mail/OWA/OWAAccount.ts, app/logic/Mail/OWA/OWAFolder.ts, app/logic/Mail/SQL/Account/SQLAccount.ts, app/logic/util/Semaphore.ts
Found by `tsc --noUnusedLocals`.
Note: There are more unused imports than those listed here, but some are e.g. for unfinished or commented out code.
=> Remove some unused imports #841

app/frontend/Util/date.ts
Found by `tsc --strictNullChecks` (11 error messages in total).
=> `fullDate` and `dateDetails` should be typed as `Intl.DateTimeFormatOptions` #841

mobile/package.json
- Configuration cache was originally used for speeding up local builds and CI builds
- On the CI builds the setup-gradle step was supposed to cache the config but it doesn't. It only caches Gradle assets.
- Now it's causing some errors and might cause more errors in the future:
```
FAILURE: Build failed with an exception.
* What went wrong:
Configuration cache problems found in this build.
1 problem was found storing the configuration cache.
- Plugin 'kotlin-android': Unsupported provider is registered as a task completion listener in 'org.gradle.build.event.BuildEventsListenerRegistry'. Configuration Cache only supports providers returned from 'org.gradle.api.services.BuildServiceRegistry' as task completion listeners.
See https://docs.gradle.org/9.0.0/userguide/configuration_cache_status …
```
=> Android build: Remove configuration cache

app/logic/Mail/ActiveSync/ActiveSyncAccount.ts
ActiveSync should be able to use other authentication methods but `login` keeps resetting the UI method to `window`.
=> ActiveSync: Don't overwrite OAuth2 settings with every login

app/frontend/MainWindow/MainWindow.svelte, app/package.json, mobile/capacitor.config.ts, mobile/package.json
- We should hide the SplashScreen as soon as the app is loaded
- Use autoHide as a fallback
=> Mobile: Hide SplashScreen as soon app is loaded

app/frontend/MainWindow/MainWindow.svelte
- On Mac, the app was blank for me because no app was not selected
- Since we use the router now, we need to set the app with `openApp()`
- But this also opens the Mail app for Mobile now when there's a Mail account logged in.
=> Desktop: Select app with openApp (#854)
